# Generated by Django 4.0.4 on 2022-06-22 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula_imo', models.CharField(max_length=20)),
                ('rua_imo', models.CharField(max_length=20)),
                ('cep_imo', models.CharField(max_length=20)),
                ('bairro_imo', models.CharField(max_length=50)),
                ('cidade_imo', models.CharField(max_length=20)),
                ('uf_imo', models.CharField(max_length=30)),
                ('tamanho_imo', models.CharField(max_length=20)),
                ('comodos_imo', models.CharField(max_length=20)),
                ('garagem_imo', models.CharField(max_length=20)),
                ('valor_imo', models.CharField(max_length=20)),
                ('tipo_imo', models.CharField(max_length=20)),
                ('status_imo', models.CharField(max_length=20)),
            ],
        ),
    ]
