# Generated by Django 4.0.4 on 2022-06-22 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=20)),
                ('rg', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=20)),
                ('sexo', models.CharField(max_length=50)),
                ('dataNascimento', models.CharField(max_length=20)),
                ('carteiraTrabalho', models.CharField(max_length=30)),
                ('salario', models.CharField(max_length=20)),
                ('pis', models.CharField(max_length=20)),
            ],
        ),
    ]
