# Generated by Django 4.0.4 on 2022-06-22 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dadosCliente', models.CharField(max_length=20)),
                ('dadosCorretor', models.CharField(max_length=20)),
                ('descricaoImovel', models.CharField(max_length=20)),
                ('valor', models.CharField(max_length=50)),
                ('documentacao', models.CharField(max_length=20)),
                ('clausulaPenal', models.CharField(max_length=30)),
            ],
        ),
    ]
